name: Create Release
on:
  push:
    branches:
      - 'main'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Sector File Version
        id: read_sector_version
        run: |
          SECTOR_FILE="Data/Sector/Hong-Kong-Sector-File.sct" 
          SECTOR_INFO=$(grep "Hong Kong Sector" "$SECTOR_FILE")
          SECTOR_ID=$(echo $SECTOR_INFO | awk -F' ' '{print $4}')
          echo "::set-output name=SECTOR_ID::$SECTOR_ID"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          tag_prefix: ""
      - name: Publish Release Draft
        id: publish_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          generate_release_notes: true
          draft: true
          prerelease: false
